language: swift
osx_image: xcode11.3
script:
  - swift test
  - xcodebuild -scheme "InstantMock iOS" -workspace InstantMock.xcworkspace/ -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.2.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^InstantMock$'
