os:
  - linux
  - osx
language: generic
sudo: required
dist: bionic
osx_image: xcode11.3
before_install:
  - chmod +x ./ci/*.sh
install:
  - ./ci/install.sh
script:
  - ./ci/script.sh
after_success:
  - ./ci/after_success.sh'
